(WIP) Made review changes suggested by Hashicorp
vmware-archive/terraform-provider-vmc pull request #18
Opened 2020-01-22 00:23 UTC by saloneerege

2020-01-23 17:25 UTC, shylasrinivas reviewed
Apart from README (for which I have some comments), rest looks good.

- We had purposely removed instructions on how to use the provider in the README since Go SDK is not public yet. Do we want to add them back for the sake of the review or comment them out or let the Hashicorp reviewer know why the README does not look complete?
- References to main.tf can be changed to examples/main.tf

2020-01-24 01:48 UTC, rchadalawada requested changes

2020-01-24 01:48 UTC, rchadalawada commented on .gitignore
> +*.tf
update this to ignore only the .tf files in the root directory

2020-01-24 01:48 UTC, rchadalawada commented on README.md
Should we specify that these instructions are for mac or linux only

2020-01-24 01:48 UTC, rchadalawada commented on README.md
> +go build -o terraform-provider-vmc
should we instead say "make"? Also, we should fix the 'go fmt' error that we are getting when we do just "make"
rchadalawad-a01:tpv rchadalawada$ make
==> Checking that code complies with gofmt requirements...
gofmt needs running on the following files:
./vmc/provider.go
You can use the command: `make fmt` to reformat code.
make: *** [fmtcheck] Error 1
rchadalawad-a01:tpv rchadalawada$ make fmt

2020-01-24 01:48 UTC, rchadalawada commented on README.md
> +* id
Org id

2020-01-24 01:48 UTC, rchadalawada commented on README.md
> +
how about "sddc region"

2020-01-24 01:48 UTC, rchadalawada commented on README.md
> +
Actually, we should move these instructions to the examples README.md and just add a reference to that here

2020-01-24 02:05 UTC, saloneerege commented on .gitignore
> +*.tf
This change was in another PR. I will rebase with master

2020-01-24 02:06 UTC, saloneerege commented on README.md
Yes I think we should.

2020-01-24 20:07 UTC, rchadalawada commented on README.md
Please add a line stating that

2020-01-28 23:38 UTC, closed without merging