Modified README in examples folder
vmware-archive/terraform-provider-vmc pull request #22
Opened 2020-01-24 00:18 UTC by saloneerege

Made changes to use variables in main.tf file and added defitions for those variables in variables.tf.

2020-01-24 00:20 UTC, saloneerege commented
Pull request title appended with WIP since I am testing my changes. This branch should not be merged until then.

2020-01-24 00:20 UTC, shylasrinivas commented on examples/README.md
> +This is an example that supports SDDC management actions like creating an SDDC ,
space before comma needs to be removed for SDDC

2020-01-24 00:20 UTC, shylasrinivas commented on examples/variables.tf
> +  description = "API token used to auntheicate when calling the VMware Cloud Services API."
fix spelling for authenticate

2020-01-24 00:31 UTC, shylasrinivas reviewed
do we want to also move num_host to variables.tf? It is set to 3 currently..

2020-01-24 01:37 UTC, rchadalawada requested changes

2020-01-24 01:37 UTC, rchadalawada commented on examples/README.md
> +* Update the `variables.tf` according to your test environment.
For completeness, please add the terraform commands also.

2020-01-24 01:37 UTC, rchadalawada commented on examples/main.tf
>    provider_type       = "AWS"
what is the use of this parameter? Why is this set to AWS?

2020-01-24 02:04 UTC, saloneerege commented on examples/main.tf
>    provider_type       = "AWS"
The provider type determines what additional properties are available based on cloud provider (description from the VMC API explorer). This is the same parameter that can be changed to ZEROCLOUD

2020-01-28 04:49 UTC, saloneerege commented on examples/README.md
> +* Update the `variables.tf` according to your test environment.
Done

2020-01-28 06:24 UTC, rchadalawada requested changes
The READMEs still need some reorg. Lets discuss tomorrow

2020-01-28 06:26 UTC, rchadalawada reviewed
You may have to rebase your branch .. I see a lot more changes than just the README

2020-01-28 06:27 UTC, saloneerege commented
> You may have to rebase your branch .. I see a lot more changes than just the README

@rchadalawada I rebased my branch with master and the changes other than the README are from the rebase.

2020-01-28 20:05 UTC, rchadalawada commented on examples/README.md
> +The following instructions assume that the required parameters have updated in [variables.tf](https://github.com/vmware/terraform-provider-vmc/blob/master/examples/variables.tf) with your infrastruct
Please correct the sentence.  -- "have been updated" or "are updated"

2020-01-28 20:06 UTC, closed without merging

2020-01-28 20:07 UTC, shylasrinivas reviewed
Can you run linter check on the code?

2020-01-28 20:07 UTC, shylasrinivas commented on vmc/resource_vmc_sddc.go
> +		d.Set("nsxt_reverse_proxy_url",sddc.ResourceConfig.NsxApiPublicEndpointUrl)
Is your local branch synced with master? I think I saw nsxt related changes in another PR which was merged earlier today.

2020-01-28 20:07 UTC, shylasrinivas commented on README.md
> +## Build the Provider
From the sample README @ https://github.com/terraform-providers/terraform-provider-null, this should be 'Building the Provider'.

2020-01-28 20:07 UTC, shylasrinivas commented on examples/README.md
> +* Update the variables required parameters api_token and org_id in [variables.tf](https://github.com/vmware/terraform-provider-vmc/blob/master/examples/variables.tf) with your infrastructure settings
remove variables from the beginning of the sentence? - change to 'Update required parameters..'