[WIP] Public IP resource
vmware-archive/terraform-provider-vmc pull request #43
Opened 2020-02-27 23:34 UTC by shylasrinivas

2020-02-28 00:51 UTC, rchadalawada commented on vmc/resource_vmc_public_ip.go
> +/* Copyright 2019 VMware, Inc.
update copyright

2020-02-28 00:53 UTC, rchadalawada commented on vmc/resource_vmc_public_ip.go
> +			Create: schema.DefaultTimeout(300 * time.Minute),
looks like the timeout is too high a value (300min?)

2020-02-28 01:00 UTC, rchadalawada commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
Don't we have to close the connection when we are done? Can we use defer?

2020-02-28 17:43 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +			Create: schema.DefaultTimeout(300 * time.Minute),
Good catch. I think I'll remove the time out part. Public IP APIs are synchronous and do not take time to create the resource.

2020-02-28 17:44 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
Since the same connector is used across resources, I don't think we need to close the connector here.

2020-02-28 17:45 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
Rather than closing the connector you might have to defer Close() the response.

2020-02-28 17:47 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
Actually we might not need to close it can you check if the API definition in the SDK handles the Close() ?

2020-02-28 17:48 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
I checked SDDC resource and vSphere resources - didn't see anything related. Can you share an example?

2020-02-28 17:50 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
https://github.com/vmware/terraform-provider-vmc/blob/master/vmc/clientconnector.go#L70 , but I think in our case we might not have to close the response since we always get the object from the API call and not the HTTP response.

2020-02-28 17:53 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	nsxVmcAwsClient := api.NewDefaultNsxVmcAwsIntegrationClient(connector)
right

2020-03-03 19:59 UTC, saloneerege commented on examples/main.tf
> +resource "vmc_publicip" "public_ip_1" {
I think the resource name should be vmc_public_ip

2020-03-03 20:06 UTC, saloneerege commented
Can you fix the Travis CI build failure

2020-03-03 20:11 UTC, saloneerege commented on examples/main.tf
> +resource "vmc_publicip" "public_ip_1" {
The resource name should be vmc_public_ip

2020-03-03 20:11 UTC, saloneerege commented on vmc/clientconnector.go
> -	if len(refreshToken) <= 0 {
Why is this check removed ?

2020-03-03 20:12 UTC, saloneerege commented on vmc/data_source_vmc_org_test.go
> +
Please fmt imports. They are not in alphabetical order

2020-03-03 20:12 UTC, saloneerege commented on vmc/provider.go
>  )
Please fmt imports. They are not in alphabetical order

2020-03-03 20:12 UTC, shylasrinivas commented on vmc/clientconnector.go
> -	if len(refreshToken) <= 0 {
I have moved it before this func is called in provider.go since its required to be set in env variable. Check changes in provider.go

2020-03-03 20:13 UTC, shylasrinivas commented on vmc/data_source_vmc_org_test.go
> +
I am using go fmt. This is auto formatted import order.

2020-03-03 20:17 UTC, shylasrinivas commented on vmc/data_source_vmc_org_test.go
> +
actually I am using go imports. It is built-in in my IDE
https://goinbigdata.com/goimports-vs-gofmt/

Along with alphabetical ordering, it also groups the imports

2020-03-03 20:22 UTC, saloneerege requested changes

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	"fmt"
Please fmt imports. They are not in alphabetical order

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +func getNSXTReverseProxyConnector() (client.Connector, error) {
I think we should move this method to a utils.go file

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
Can we call the variable err and not createErr

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +		Id:          &uuid,
Can the id be a variable that the user provides and if it is not provided by the user then the code generates one.

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	var forceDelete bool = true
Why do we need to set the forceDelete value ? Can this be provided by the user ?

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_sddc.go
> +	"log"
Please fmt imports

2020-03-03 20:22 UTC, saloneerege commented on vmc/resource_vmc_sddc_test.go
> +	"os"
Please format the imports

2020-03-03 20:25 UTC, shylasrinivas commented on vmc/resource_vmc_sddc_test.go
> +	"os"
what is the recommendation by HashiCorp on formatting imports?

2020-03-03 20:26 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	var forceDelete bool = true
We don't want this bool to be part of the resource. API expects a boolean which is being set here.

2020-03-03 20:26 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +		Id:          &uuid,
APIs do not expect ID to be provided by the user in case of create, uuid is generated as part of IP creation

2020-03-03 20:27 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +		Id:          &uuid,
behavior has been tested by Gilles

2020-03-03 20:27 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
the reason I have createErr is coz there is already an error defined above which is returned in case of connection err and that cannot be used here

2020-03-03 20:27 UTC, saloneerege commented on vmc/data_source_vmc_org_test.go
> +
Can you remove the extra line and see if it changes the import grouping ? The one we have followed everywhere in the code is just the one that puts all the imports in the alphabetical order.

2020-03-03 20:32 UTC, saloneerege commented on vmc/data_source_vmc_org_test.go
> +
https://goinbigdata.com/goimports-vs-gofmt/ Based on this since it groups the imports separately based on third party imports. I will use goimports too. I used to use go fmt but goimports seems to be better.

2020-03-03 20:34 UTC, saloneerege commented on vmc/resource_vmc_sddc_test.go
> +	"os"
I dont think they have one

2020-03-03 20:35 UTC, saloneerege commented on vmc/resource_vmc_sddc_test.go
> +	"os"
Google provider seems to be using goimports and nsxt seems to be using go fmt. I checked only 1 file in each . Lets use goimports moving forward

2020-03-03 20:38 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
Why cant the same err be used again ?

2020-03-03 20:41 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
because I am using := assignment instead of =
I have to use := since I need publicIp ID to set in the resource

2020-03-03 20:42 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
recommended testing the assignment operators if you have doubts

2020-03-03 20:45 UTC, shylasrinivas commented on vmc/resource_vmc_public_ip.go
> +	publicIp, createErr := nsxVmcAwsClient.CreatePublicIp(uuid, *publicIpModel)
ignore my previous comments, I am testing what you recommended

2020-03-03 20:45 UTC, saloneerege commented on vmc/data_source_vmc_org_test.go
> +
Travis CI build might however fail if we use  go imports and not go fmt. Can you check that too ?

2020-03-03 22:20 UTC, saloneerege commented on vmc/resource_vmc_public_ip.go
> +func getNSXTReverseProxyConnector() (client.Connector, error) {
For now, lets keep this here

2020-03-03 22:21 UTC, saloneerege approved these changes

2020-03-03 22:23 UTC, merged